### ISSUE TITLE
关于神经网络象棋引擎

### ISSUE THREAD

**Issue by shuangqiao999** [RayZhhh/vliang-chinesechess-cpp#1]
你好 有个神经网络象棋引擎项目你有兴趣参加吗 棋力非常不错 项目地址https://github.com/PikaCat-OuO/Pikafish
QQ群:757543072

**Comment by calcitem** [comment]
你好！为啥不基于 https://github.com/ianfab/Faity-Stockfish 项目来做呢？基于鳕鱼实现了象棋引擎，已经很成熟了。支持 NNUE。
